// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::subjects;

#[derive(Queryable, Insertable, Debug)]
pub struct Subject {
    pub id: String,
    pub subject: String,
}