// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::subjects;
use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};

#[derive(Queryable, Insertable, Debug, PartialEq)]
pub struct Subject {
    pub id: String,
    pub subject: String,
    pub dt: NaiveDateTime,
}

impl Subject {
    pub fn to_response(self) -> SubjectResponse {
        SubjectResponse {
            id: self.id,
            subject: self.subject
        }
    }
}

#[derive(Serialize, Deserialize)]
pub struct SubjectResponse {
    pub id: String,
    pub subject: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewSubject {
    pub subject: String,
    pub dt: String,
}